version: '3'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-16T16-07-38Z
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_DOMAIN=minio
    networks:
      net:
        aliases:
          - ct-lamp.minio
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
  dynamo:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    image: "amazon/dynamodb-local:latest"
    working_dir: /home/dynamodblocal
    ports:
      - "127.0.0.1:8000:8000"
    user: root
    volumes:
      - dynamo_data:/data
    networks:
      net:
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:8000"]
      interval: 5s
  setup:
    build:
      context: setup
    entrypoint: /bin/sh
    command: /bin/setup.sh
    depends_on:
      minio:
        condition: service_healthy
      dynamo:
        condition: service_healthy
    networks:
      net:
  sunlight-setup: &sunlight-setup
    build:
      context: sunlight
      args:
        GO_VERSION: 1.21.5
    volumes:
      - cache:/cache
      - type: bind
        source: ./sunlight/etc
        target: /etc/sunlight
    ports:
      - "127.0.0.1:7000:7000"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    command: /bin/sunlight -create -c /etc/sunlight/sunlight.yaml
    depends_on:
      setup:
        condition: service_completed_successfully
    networks:
      net:
  sunlight:
    <<: *sunlight-setup
    command: /bin/sunlight -c /etc/sunlight/sunlight.yaml
    depends_on:
      sunlight-setup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:7000"]
      interval: 5s
  preloader:
    command:
      - /bin/preloader
      - -source_log_uri
      - https://sapling.ct.letsencrypt.org/2024h1
      - -target_log_uri
      - http://sunlight:7000/lamp
    build:
      context: preloader
      args:
        GO_VERSION: 1.21.5
    depends_on:
      sunlight:
        condition: service_healthy
    networks:
      net:
volumes:
  minio_data:
  dynamo_data:
  cache:
networks:
  net:
