name: Sunlight Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "mcpherrinm/sunlight-woodpecker"
          path: "woodpecker/sunlight-woodpecker"
      - uses: actions/checkout@v4
        with:
          repository: "FiloSottile/sunlight"
          path: "sunlight/sunlight"
      - run: ./test.sh
